### ISSUE TITLE
juicy-tile-tree not always rendered when editing juicy-tile-grid

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#37] opened 2014-06-25 12:49 UTC
When editor is used with `<juicy-tile-grid>` (especially that contains other nested  `<juicy-tile-grid>`), the tree is not always rendered.

**Comment by tomalec** [comment] 2014-07-09 11:43
[juicy-tile-editor.js#L146](https://github.com/Juicy/juicy-tile-editor/blob/gh-pages/src/juicy-tile-editor.js#L146) seems to be the reason, as `.editedTiles` is usually not the ones rendered in tree.

**Comment by tomalec** [comment] 2014-07-11 10:06
There are two somehow separated issues:
1. Tree is empty on page load, it requires clicking on a tile.
2. After clicking on nested `<juicy-tile-list>` or `-grid` (not on a tile, but on grid background) tree will not show at all.

**Comment by warpech** [comment] 2015-05-07 14:58
1. Is still reproducible and should be easy to fix. When a element is selected, the tree displays all `juicy-tile-list` elements in the document anyway.
2. Seems to be fixed.

@tomalec can you confirm the above? @miyconst can you fix 1. after @tomalec confirms?

**Comment by tomalec** [comment] 2015-05-07 20:41
Confirmed, especially that we currently do not have any juicy-tile-lists hidden in ShadowDOM.

**Comment by warpech** [comment] 2015-05-08 07:29
Then green light for fixing 1., and then https://github.com/Polyjuice/Launcher/issues/123

**Comment by miyconst** [comment] 2015-05-08 16:50
@tomalec I have added `this.treeRefresh();` to `domReady` of `juicy-tile-editor`, but it does not show entire tree of the tiles.

Works fine in Launcher, but not here: `/juicy-tile-editor/examples/juicy-tiles-grid-editor.html`. That is why I put the call inside a timeout, now it works everywhere.

Should I move it somewhere else and refresh the tree without timeout?

**Comment by miyconst** [comment] 2015-05-20 16:42
@warpech, @tomalec any input for this issue? Can I close it?

**Comment by warpech** [comment] 2015-05-27 09:04
Problem solved for me. 

Extra Clean Solutions Department (@tomalec) might not like the timeout so I will let him speak or close the issue :)

**Comment by warpech** [comment] 2015-06-05 09:06
Ping @tomalec - can this be closed?

**Comment by tomalec** [comment] 2015-06-05 11:11
For Polymer Element there is a `.async` method, but as we are moving away from Polymer `setTimeout` works better.

I suspect the reason why it didn't work for editor demo without `setTimeout` was that the juicy-tiles list was not yet in DOM. Current solution does not cover the cases when `juicy-tile-list` will appear later.
As mutation observer may be expensive, I think we can agree on such behavior - editor shows only lists available in DOM at attached time, if someone would like to refresh it, he/she could call `.treeRefresh()` manually.

**Comment by warpech** [comment] 2015-06-05 11:32
Then maybe `setTimeout` should have been added in the demo code, not inside `juicy-tile-editor`?

**Comment by tomalec** [comment] 2015-06-05 13:02
Or open on click, or maybe just put it after tiles in DOM?

2015-06-05 13:32 GMT+02:00 Marcin Warpechowski notifications@github.com:

**Comment by warpech** [comment] 2015-06-05 13:57
@miyconst could you check if the above would work instead of using `setTimeout`?

**Comment by miyconst** [comment] 2015-06-05 17:11
Currently `<juicy-tile-editor selectionmode watchedtagnames="['JUICY-TILE-LIST', 'JUICY-TILE-GRID']" class="max-height"></juicy-tile-editor>` is at the very bottom of the Launcher and inside `<template if="{{editingMode$}}">`.

This means that `juicy-tile-editor` is added to the page by user's click and after all other elements.

**Comment by miyconst** [comment] 2015-06-19 07:49
Ping @warpech & @tomalec.

**Comment by miyconst** [comment] 2015-08-10 05:11
@warpech, @tomalec can this issue be closed?

**Closed as completed** 2015-08-23 15:49 UTC
Labels: bug
